use_frameworks!

target 'MRPullToRefreshLoadMore_Example' do
  pod 'MRPullToRefreshLoadMore', :path => '../'

  target 'MRPullToRefreshLoadMore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
